#!/usr/bin/env bash
# does multiple thingzzz

trap "echo I hate the kill command; rm -f /var/run/myscript.pid; exit 0" SIGTERM

trap "echo Y U no love me?!" SIGINT

trap "rm -f /var/run/myscript.pid; exit 0" SIGQUIT

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
while :
do
    echo "To infinity and beyond"
	sleep 2
done

